# Generated by Django 5.0.4 on 2024-05-16 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
